# Generated by Django 3.1.7 on 2022-01-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='focus_area',
            new_name='user_focus_area',
        ),
    ]
