# Generated by Django 3.1.7 on 2022-01-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220126_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_height',
            field=models.FloatField(default=0),
        ),
    ]
