# Generated by Django 3.1.7 on 2022-02-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220128_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Exercise_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500)),
                ('exercise_name', models.CharField(max_length=500)),
                ('exercise_playlist', models.IntegerField(default=0)),
                ('exercise_count', models.IntegerField(default=0)),
                ('exercise_duration', models.FloatField(default=0)),
                ('exercise_total_duration', models.FloatField(default=0)),
                ('exercise_calorie_burnt', models.FloatField(default=0)),
                ('exercise_weight_loss', models.FloatField(default=0)),
                ('current_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
