# Generated by Django 3.1.7 on 2022-02-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_user_exercise_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_exercise_info',
            name='current_time',
            field=models.DateTimeField(),
        ),
    ]
