# Generated by Django 3.2 on 2022-02-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220209_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('exercise_jj', models.IntegerField(default=0)),
                ('exercise_ac', models.IntegerField(default=0)),
                ('exercise_kp', models.IntegerField(default=0)),
                ('exercise_sar', models.IntegerField(default=0)),
                ('exercise_squats', models.IntegerField(default=0)),
                ('exercise_bl', models.IntegerField(default=0)),
                ('exercise_cs', models.IntegerField(default=0)),
            ],
        ),
    ]
