# Generated by Django 3.2 on 2022-02-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_playlist_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_exercise_info',
            name='exercise_playlist',
        ),
        migrations.AddField(
            model_name='playlist_check',
            name='current_date',
            field=models.DateField(),
        ),
    ]
