# Generated by Django 3.2 on 2022-02-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220221_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist_check',
            name='current_date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
