# Generated by Django 3.2 on 2022-02-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_playlist_check_current_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist_check',
            name='current_date',
        ),
    ]
