# Generated by Django 3.2 on 2022-02-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_playlist_check_current_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_exercise_info',
            name='exercise_total_duration',
        ),
        migrations.AddField(
            model_name='playlist_check',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
