# Generated by Django 3.2 on 2022-02-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20220221_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_bmr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_height_ft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_height_in',
            field=models.IntegerField(default=0),
        ),
    ]
