# Generated by Django 3.1.7 on 2022-03-12 07:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_diet_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_menu',
            name='diet_breakfast',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='diet_menu',
            name='diet_dinner',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='diet_menu',
            name='diet_lunch',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='diet_menu',
            name='diet_snacks',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
