# Generated by Django 3.1.7 on 2022-03-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20220312_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_menu',
            name='diet_breakfast',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diet_menu',
            name='diet_dinner',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diet_menu',
            name='diet_lunch',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diet_menu',
            name='diet_snacks',
            field=models.TextField(blank=True),
        ),
    ]
